server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql:///StudentScoreManager?useUnicode=true&characterEncoding=utf-8
    username: root
    password: newpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
  #thymeleaf引擎模板
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
#    默认是开启状态
    enabled: true
  # 热部署
  devtools:
    restart:
      enabled: true
      # 设置重启目录
      additional-paths: src/main/java
      # 设置classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: static/**
#      additional-exclude: thymeleaf/**
#mybatis:
#  mapper-locations: classpath:/mapper/
#  type-aliases-package: com.ken.stuscoremanager.entity
# 注解方式只需要找到对应的包并扫描即可
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helper-dialect: mysql
  # 是否启用分页合理化，如果启用，当前pagenum < 1 时，会自动查询第一页的数据，当pagenum > pages 时，自动查询最后一页数据；不启用的，以上两种情况都会返回空数据
  reasonable: true
  # 默认值为false，分页插件会从查询方法的参数值中，自动根据上面params配置的字段中取值，查找到合适的值时就会自动分页
  support-methods-arguments: true
  # 用于从对象中根据属性名取名，例如可以设置pageNum，pageSize，count，pageSizeZero....
  params: count=countsql
# 自定义文件上传和下载路径
management:
  path: F:\模拟上传和下载文件\
  #  文件超过1M可以在yml位置加上max-file-size：10M
  max-file-size: 10M



#  以下为分页助手的部分设置
#
#
#  # dialect: ①
#  # 分页插件会自动检测当前的数据库链接，自动选择合适的分页方式（可以不设置）
#  helper-dialect: mysql
#  # 上面数据库设置后，下面的设置为true不会改变上面的结果（默认为true）
#  auto-dialect: true
#  page-size-zero: false # ②
#  reasonable: true # ③
#  # 默认值为 false，该参数对使用 RowBounds 作为分页参数时有效。（一般用不着）
#  offset-as-page-num: false
#  # 默认值为 false，RowBounds是否进行count查询（一般用不着）
#  row-bounds-with-count: false
#  #params: ④
#  #support-methods-arguments: 和params配合使用，具体可以看下面的讲解
#  # 默认值为 false。设置为 true 时，允许在运行时根据多数据源自动识别对应方言的分页
#  auto-runtime-dialect: false # ⑤
#  # 与auto-runtime-dialect配合使用
#  close-conn: true
#  # 用于控制默认不带 count 查询的方法中，是否执行 count 查询，这里设置为true后，total会为-1
#  default-count: false
